# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       polkit-qt5-1

# >> macros
# << macros

Summary:    Qt bindings for PolicyKit
Version:    0.103.1.20140228.3a5f879
Release:    1
Group:      System/Libraries
License:    GPLv2+
URL:        https://projects.kde.org/projects/kdesupport/%{name}
Source0:    %{name}-%{version}.tar.bz2
Source100:  polkit-qt5-1.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(polkit-agent-1)
BuildRequires:  pkgconfig(polkit-gobject-1)
BuildRequires:  cmake
BuildRequires:  extra-cmake-modules
BuildRequires:  cmake

%description
PolicyKit is an application-level toolkit for defining and handling the policy
that allows unprivileged processes to speak to privileged processes.

It is a framework for centralizing the decision making process with respect to
granting access to privileged operations (like calling the HAL Mount() method)
for unprivileged (desktop) applications.

libpolkit-qt-1 provides convenience classes and methods for Qt/KDE
applications that want to use PolicyKit.

This package contains the files necessary for running applications that use
the libpolkit-qt-1 library.


%package devel
Summary:    PolicyKit Qt development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   pkgconfig

%description devel
PolicyKit is an application-level toolkit for defining and handling the policy
that allows unprivileged processes to speak to privileged processes.

It is a framework for centralizing the decision making process with respect to
granting access to privileged operations (like calling the HAL Mount() method)
for unprivileged (desktop) applications.

libpolkit-qt-1 provides convenience classes and methods for Qt/KDE
applications that want to use PolicyKit-1.

This package contains the development libraries and headers.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
cd upstream
# << build pre

%cmake .  \
    -DCMAKE_INSTALL_PREFIX="%{_prefix}" \
    -DCMAKE_C_COMPILER:FILEPATH="cc" \
    -DCMAKE_CXX_COMPILER:FILEPATH="g++" \
    -DCMAKE_C_FLAGS="%{optflags} -fvisibility=hidden -fvisibility-inlines-hidden" \
    -DCMAKE_CXX_FLAGS="%{optflags} -fvisibility=hidden -fvisibility-inlines-hidden" \
    -DCMAKE_SKIP_RPATH=ON \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DCMAKE_SKIP_RPATH:BOOL=OFF \
    -DCMAKE_USE_RELATIVE_PATHS=ON \
    -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" \
    -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" \
    -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" \
    -DUSE_QT5:bool=ON

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd upstream
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
#%doc AUTHORS COPYING README
%{_libdir}/libpolkit-qt5-agent-1.so.1*
%{_libdir}/libpolkit-qt5-core-1.so.1*
%{_libdir}/libpolkit-qt5-gui-1.so.1*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/polkit-qt5-1/PolkitQt1/ActionDescription
%{_includedir}/polkit-qt5-1/PolkitQt1/Agent/Listener
%{_includedir}/polkit-qt5-1/PolkitQt1/Agent/Session
%{_includedir}/polkit-qt5-1/PolkitQt1/Authority
%{_includedir}/polkit-qt5-1/PolkitQt1/Details
%{_includedir}/polkit-qt5-1/PolkitQt1/Gui/Action
%{_includedir}/polkit-qt5-1/PolkitQt1/Gui/ActionButton
%{_includedir}/polkit-qt5-1/PolkitQt1/Gui/ActionButtons
%{_includedir}/polkit-qt5-1/PolkitQt1/Identity
%{_includedir}/polkit-qt5-1/PolkitQt1/Subject
%{_includedir}/polkit-qt5-1/PolkitQt1/TemporaryAuthorization
%{_includedir}/polkit-qt5-1/polkitqt1-actiondescription.h
%{_includedir}/polkit-qt5-1/polkitqt1-agent-listener.h
%{_includedir}/polkit-qt5-1/polkitqt1-agent-session.h
%{_includedir}/polkit-qt5-1/polkitqt1-authority.h
%{_includedir}/polkit-qt5-1/polkitqt1-details.h
%{_includedir}/polkit-qt5-1/polkitqt1-export.h
%{_includedir}/polkit-qt5-1/polkitqt1-gui-action.h
%{_includedir}/polkit-qt5-1/polkitqt1-gui-actionbutton.h
%{_includedir}/polkit-qt5-1/polkitqt1-gui-actionbuttons.h
%{_includedir}/polkit-qt5-1/polkitqt1-identity.h
%{_includedir}/polkit-qt5-1/polkitqt1-subject.h
%{_includedir}/polkit-qt5-1/polkitqt1-temporaryauthorization.h
%{_includedir}/polkit-qt5-1/polkitqt1-version.h
%{_libdir}/cmake/PolkitQt5-1/PolkitQt5-1Config.cmake
%{_libdir}/cmake/PolkitQt5-1/PolkitQt5-1ConfigVersion.cmake
%{_libdir}/libpolkit-qt5-agent-1.so
%{_libdir}/libpolkit-qt5-core-1.so
%{_libdir}/libpolkit-qt5-gui-1.so
%{_libdir}/pkgconfig/polkit-qt5-1.pc
%{_libdir}/pkgconfig/polkit-qt5-agent-1.pc
%{_libdir}/pkgconfig/polkit-qt5-core-1.pc
%{_libdir}/pkgconfig/polkit-qt5-gui-1.pc
# << files devel
